Feat: Add support for Pixart-Sigma
PipeFusion/PipeFusion pull request #131
Opened 2024-07-18 12:42 UTC by Eigensystem

#115 
- [x] support pixart-sigma
- [x] fix multiple resolution runtime error

2024-07-18 19:25 UTC, Eigensystem commented
Refactor dp implementation, solved #98

2024-07-19 03:01 UTC, feifeibear requested changes

2024-07-19 03:01 UTC, feifeibear commented on lagecy/pipefuser/logger.py
> +# Adapted from
Please remove catcus.png!

2024-07-19 05:41 UTC, feifeibear approved these changes

2024-07-19 05:44 UTC, merged